# Generated by Django 3.2.7 on 2021-10-01 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentAccount',
            fields=[
                ('name', models.CharField(max_length=167, primary_key=True, serialize=False, verbose_name='Название счета')),
                ('overdraft', models.BooleanField(verbose_name='Овердрафт счета')),
                ('balance', models.FloatField(default=0.0, verbose_name='Баланс счета')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_amount', models.FloatField(verbose_name='Сумма перевода')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donor', to='billing_app.currentaccount', verbose_name='Счет донора')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipient', to='billing_app.currentaccount', verbose_name='Счет реципиента')),
            ],
        ),
    ]
