# Generated by Django 3.2.7 on 2021-10-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentaccount',
            name='name',
            field=models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='Название счета'),
        ),
    ]
