# Generated by Django 3.2.7 on 2021-10-01 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0002_alter_currentaccount_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currentaccount',
            options={'verbose_name': 'Текущий счет', 'verbose_name_plural': 'Текущие счета'},
        ),
        migrations.AlterModelOptions(
            name='transactions',
            options={'verbose_name': 'Транзакция', 'verbose_name_plural': 'Транзакции'},
        ),
    ]
